# Pages CMS Configuration
# This file defines how content is managed through Pages CMS

# Content collections
collections:
  - name: posts
    label: Blog Posts
    description: Blog posts for the website
    path: content/posts
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: excerpt
        label: Excerpt
        type: text
        required: true
        description: A short summary of the post
      - name: author
        label: Author
        type: string
        default: Matthew Coleman
      - name: tags
        label: Tags
        type: list
        description: Add tags to categorize your post
      - name: body
        label: Content
        type: markdown
        required: true

  - name: pages
    label: Pages
    description: Static pages
    path: content/pages
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: body
        label: Content
        type: markdown
        required: true

# Media settings
media:
  path: public/images
  public_path: /images

# Site settings
settings:
  title: Matthew Coleman's Website
  description: Personal website and blog
  url: https://slider003.github.io/matthew-coleman/
